---
# tasks file for ssh-user-keygen
- name: Ensure ~/.ssh directory exists
  become: true
  become_user: root
  with_items: '{{ ssh_user_target_users }}'
  ansible.builtin.file:
    owner: '{{ item.u }}'
    path: '{{ item.hd | default(ssh_user_default_homedir + "/" + item.u) }}/.ssh'
    state: directory
    mode: '700'

- name: Authorize public key...
  become: true
  become_user: root
  with_items: '{{ ssh_user_target_users }}'
  ansible.builtin.lineinfile:
    create: true
    owner: '{{ item.u }}'
    dest: '{{ item.hd | default(ssh_user_default_homedir + "/" + item.u) }}/.ssh/authorized_keys'
    line: '{{ lookup("file", ssh_user_pubkey) }}'
    mode: '644'
